config/routes.rb
Prelaunchr::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "users#new"

  resources :users do
    collection do
      get :faq
      get :jobs
      get :partner
      get :policy
      get :presskit
      get :terms
    end
  end

  match 'refer-a-friend' => 'users#refer'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match 'venues/faq' => 'venues#faq'
  match 'venues/index' => 'venues#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/concerns/tokened.rb
module Tokened

  extend ActiveSupport::Concern

  included do
    after_initialize do
      self.token = generate_token if self.token.blank?
    end
  end

  private
    def generate_token
      loop do
        key = SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz')
        break key unless self.class.find_by(token: key)
      end
    end
end

app/models/ip_address.rb
class IpAddress < ActiveRecord::Base
  attr_accessible :address, :count
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :referrer, :class_name => "User", :foreign_key => "referrer_id"
  has_many :referrals, :class_name => "User", :foreign_key => "referrer_id"  
  attr_accessible :email

  validates :email, :uniqueness => true, :format => { :with => /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/i, :message => "Invalid email format." }
  validates :referral_code, :uniqueness => true

  before_create :create_referral_code
  after_create :send_welcome_email

  # user = User.create
  # user.token1 => "asd"

  REFERRAL_STEPS = [
    {
      'count' => 7,
      "html" => "Free Grotto Hour",
      "class" => "two"
      # "image" =>  ActionController::Base.helpers.asset_path("home/pit_1.png")
    },
    {
      'count' => 15,
      "html" => "Free Grotto Hour<br>For You And 3 Friends",
      "class" => "three"
      # "image" => ActionController::Base.helpers.asset_path("home/pit_truggle.png")
    },
    {
      'count' => 25,
      "html" => "Free Grotto<br>For A Month",
      "class" => "four"
      # "image" => ActionController::Base.helpers.asset_path("home/pit_stuggle_fast.png")
    }
    
  ]

  # def self.from_omniauth(auth)
  #   where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  #     user.provider = auth.provider
  #     user.uid = auth.uid
  #     user.name = auth.info.name
  #     user.oauth_token = auth.credentials.token
  #     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  #     user.save!
  #   end
  # end
  
  private

  def create_referral_code
    referral_code = SecureRandom.hex(5)
    @collision = User.find_by_referral_code(referral_code)

    while !@collision.nil?
      referral_code = SecureRandom.hex(5)
      @collision = User.find_by_referral_code(referral_code)
    end

    self.referral_code = referral_code
  end

  def send_welcome_email
    UserMailer.delay.signup_email(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :current_user

  protected
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end   

  def authenticate_user!    
    if current_user.nil?
      redirect_to root_path and return
    end
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
   # before_filter :authenticate_user!, only: [:new]

  def new
    @bodyId = 'home'
    @is_mobile = mobile_device?    

    @user = User.new
  end

  def create
    # Get user to see if they have already signed up
    @user = User.find_by_email(params[:user][:email]);
    # If user doesnt exist, make them, and attach referrer
    if @user.nil?
      cur_ip = IpAddress.find_by_address(request.env['HTTP_X_FORWARDED_FOR'])

      if !cur_ip
        cur_ip = IpAddress.create(
          :address => request.env['HTTP_X_FORWARDED_FOR'],
          :count => 0
        )
      end

      # if cur_ip.count > 2
      #   return redirect_to root_path, notice: 'You tried to sign up twice with same ip address'
      # else
      #   cur_ip.count = cur_ip.count + 1
      #   cur_ip.save
      # end

      referred_by = User.find_by_referral_code(params[:ref])

      if referred_by
        referred_by.referral_registered_number += 1
        referred_by.save
      end

      @user = User.new(:email => params[:user][:email])

      if referred_by.present?
        @user.referrer = referred_by
      end

      @user.save

    end

    session[:user_id] = @user.id

    # Send them over refer action
    if @user
      redirect_to '/refer-a-friend'
    else
      redirect_to root_path, :alert => "Something went wrong!"
    end
  end

  def refer
    @bodyId = 'refer'
    @is_mobile = mobile_device?

    if current_user.nil?
      format.html { redirect_to root_path, :alert => "Something went wrong!" }
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  layout "venues_faq", only: [:faq]
  layout "venues_index", only: [:index]
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= @bodyId %>">
  <head>
    <title>Grotto</title>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0">
    <% if @is_mobile %>
        <% if @bodyId == 'home' %>
          <meta name="viewport" content="width=1600" />
        <% else %>
          <meta name="viewport" content="width=1120" />
        <% end %>
    <% end %>

    <script src="//cdn.optimizely.com/js/2520960085.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic,600italic' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'home/favicon.ico' %>
    <script>
      !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
      n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
      document,'script','//connect.facebook.net/en_US/fbevents.js');

      fbq('init', '779098715511025');
      fbq('track', "PageView");
    </script>
    <noscript>
      <img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=779098715511025&ev=PageView&noscript=1"
      />
    </noscript>
    <script> 
      fbq('track', 'CompleteRegistration');
    </script>
    <%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= @bodyId %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/venues_faq.html.erb
<!doctype html>
<html>
<head>
<script src="//cdn.optimizely.com/js/2520960085.js"></script>
<title>Grotto | FAQ</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic,600italic' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= favicon_link_tag 'home/favicon.ico' %>
<%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/venues_index.html.erb
<!doctype html>
<html>
<head>
<script src="//cdn.optimizely.com/js/2520960085.js"></script>
<title>Grotto</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,400italic,300italic,600italic' rel='stylesheet' type='text/css'>
<link href="/assets/style_venue.css" rel="stylesheet" type="text/css" />
<%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= favicon_link_tag 'home/favicon.ico' %>
<%= csrf_meta_tags %>

</head>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69119501-1', 'auto');
  ga('send', 'pageview');

</script>
<body>
  <%= yield %>

  <script>
  
  $(function(){
    $("#carousel-our-testimonials").owlCarousel({
      autoPlay: 3000,
      stopOnHover: true,
      navigation: false,
      paginationSpeed: 1000,
      goToFirstSpeed: 100,
      singleItem: true,
      autoHeight: true,
      transitionStyle: "fade"
    });  
  });
  
  </script>
</body>
</html>

app/views/users/new.html.erb
<header id="header">
  <div class="container">     
    <div class="header-content">   
      <div class="header-text">
        <div class="logo">
          <h6 class="venue_page">          
            <%= link_to 'Are you a bar owner?', venues_index_path %>
          </h6>
          <%= image_tag 'home/main-logo2.png', :class => 'main_logo' %>
        </div> 
        <div class="box">
          <h1>$10 for an hour-long open bar</h1>  
        </div> 
        <p> Wherever you want, whenever you want <br> <span class="second_line">Tons of locations across Manhattan and Brooklyn </span></p>             
      </div>
    </div>
  </div>
  <section class="registration content-padding" id="newsletter">
    <div class="container registration-content wow fadeInDown">
      <%= image_tag 'home/main_icon.png', :class => 'mail_icon' %>
      <h3 class="newsletter_text ">Be the first to know</h3>
      <div class="registration-form">
        <%= form_for @user, :html => {:onsubmit => "return validateForm();"} do |f| %>
          <%= hidden_field_tag :ref, params[:ref] %>
          <%= f.text_field :email, :placeholder => "Enter Email", :class => 'email_form', :id => 'fieldEmail' %>
          <%= f.submit 'Step Inside!', :class => "btn newsletter-submit", :id => "newsletter_button" %>
        <% end %>
      </div>                
    </div>  
  </section>    
</header>
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <%= image_tag 'home/footer_logo.png', :class => 'footer_logo' %>
      </div>  
    </div> 
    <a href="https://www.facebook.com/Grotto-882215308529091/?fref=ts">
      <%= image_tag 'home/facebook.png', :class => 'facebook' %>
    </a>
    <a href="mailto:team@grottoapp.com">
      <%= image_tag 'home/main_icon.png', :class => 'mail_us' %>
    </a>
    <div class="row">
      <div class="col-sm-3">
        <%= link_to 'Faq', faq_users_path %>
      </div>
      <div class="col-sm-3">
        <%= link_to 'Partner with Grotto', partner_users_path %>
      </div>
      <div class="col-sm-3">
        <%= link_to 'Terms', terms_users_path %>
      </div>
      <div class="col-sm-3">
        <%= link_to 'Privacy Policy' %>
      </div>
    </div> 
  </div>     
</footer>
<script>
  function validateForm() {
    var x = document.getElementById('fieldEmail').value;
    if (x == null || x == "") {
      alert("Email Name must be filled out");
      return false;
    }
  }
</script>

app/views/users/refer.html.erb
<div id="site_wrapper">
  <div class="home-header">
    <div class="header-top text-center">
      <%= image_tag 'home/logo.png' %>
      <span>THANK YOU FOR SIGNING UP</span>
    </div>
  </div>
  <div class="row refer-wrapper">
    <div class="col-md-6 col-sm-12 wrapper-left">
      <div class="col-md-6">
        <span class="wrapper-left-text">SHAVING IS EVOLVING</span>
      </div>
      <div class="col-md-6 wrapper-left-dog">
        <%= image_tag 'home/dog.png' %>
      </div>
    </div>
  <div class="col-md-6 col-sm-12 wrapper-right">
    <div class="share-wrap">
      <p class="subtitle brandon">DON'T LEAVE YOUR FRIEDNS BEHIND</p>
      <p class="why brandon">INVITE FRIENDS & EARN PRODUCT</p>
      <p class="subtitle brandon">Share your unique link via email, Facebook<br>or Twitter and earn Grotto's tasting hour for<br>each friend who signs up.</p>
      <div class="copy-link brandon">grottoapp.herokuapp.com/?ref=<%= current_user.referral_code %></div>
      <div class="social-links">
        <a href="http://www.facebook.com" class="fb" target="_blank"></a>
        <div class="sep"></div>
        <a href="http://twitter.com/" class="twit" target="_blank"></a>
      </div>
    </div>  
  </div>
</div>

<% 
  referrals_count = current_user.referrals.count
  stops = User::REFERRAL_STEPS
  found = nil
  stops.reverse_each do |stop|
    if stop["count"] <= referrals_count and !found
      stop["selected"] = true
      found = stop
    else
      stop["selected"] = false
    end
  end
%>
<div class="row prizes <% if found %>prize-<%= found["class"] %><% end %>">

  <div class="row page-content">
    <p class="callout brandon">Here's How It Works:</p>
    <div class="row" style="padding-left: 25px; padding-right: 25px;">
      <ul class="products row">
        <div class="col-xs-3 col-xxs-12">
          <li class="title brandon text-center">
            <div>
              <span class="friends">FRIENDS JOINED</span>
            </div>
            <div class="earned">
              <span class="rewards">GROTTO HOURS <br>EARNED</span>
            </div>  
          </li>
        </div>
        
        <% stops.each do |stop| %>
          <div class="col-xs-3 col-xxs-12">
            <li class="product brandon text-center <% if stop["selected"] %>selected<% end %> <% if stop["class"] == 'five' %>last<% end %>">
              <div class="circle"><%= stop["count"] %></div>
              <div class="sep"></div>
              <span>
                <div class="menu">
                  <%= stop["html"].html_safe %>
                </div>
              </span>
              <!-- <div class="tooltip">
                <img src="<%= stop["image"] %>" height="254">
              </div> -->
            </li>
          </div>
        <% end %>
      </ul>
      <div class="progress">
        <div class="mover">
          <div class="bar clearfix"></div>
        </div>
      </div>
      <% 
        words = ''
        if referrals_count == 1
          words = 'friend has'
        elsif 
          words = 'friends have'
        end
      %>
      </div>
    </div>
    <div class="row">
      <% if referrals_count == 0 %>
        <p class="place brandon"><span>No</span> friends have joined yet...</p>
      <% else %>
        <p class="place brandon"><span><%= referrals_count %></span> <%= words %> joined</p>
      <% end %>
      <p class="check brandon">Keep checking</p>
    </div>
</div>
 

app/views/venues/faq.html.erb
<header id="header" class="custom">
    <div class="container">
      <div class="logo text-center">
        <a href="index.html">
          <%=image_tag 'home/main-logo2.png', :style => 'width:60%; max-width:200px;', :id => 'pineapple' %>
        </a>
      </div> 
      <div class="row">
        <div class="col-sm-12 text-center">
          <h1>FAQ</h1>              
        </div>
      </div>    
    </div>  
</header>

<div id="site-wrap">

  <!--General text-->
  <section class="general-text text-padding">
      <div class="container">
          <div class="row">
              <div class="col-sm-12">
                  <div class="text-content">
                      <h2>So Grotto is a Happy Hour? </h2>
            <h5>Sort of. Your Grotto price can move over the course of the night, so while you may want to use Grotto to boost your happy hour traffic, Grotto is just as useful later in the night. In fact, Grotto is great when you are slammed because it is about 3 times faster than ringing a normal drink, charging a card and waiting for a signature. Grotto keeps your staff selling drinks, not waiting on tabs.</h5>
          </div>
                    <div class="border"></div>
                  <div class="text-content">
                      <h2>Where can I see how much we’re making?</h2>
            <h5>You can always login to your sales dashboard on venues.grottoapp.com. In addition, you’ll get an automatic manager-report every night with the number of patrons and each amount broken out, from Venue Revenue to Staff Gratuity to Tax, all in one place.</h5>
          </div>
                    <div class="border"></div>
                  <div class="text-content">
                      <h2>How do I get paid?</h2>
            <h5>Grotto pays venues twice-weekly through direct deposit or physical check. As you know, you’ll get a Manager Report every night and then the funds will transfer twice a week. We’re working to increase this to daily transfers and we’ll be there soon!</h5>
          </div>
                    <div class="border"></div>  
                  <div class="text-content">
                      <h2>Can people cheat with a screenshot?</h2>
            <h5>The Grotto Drinking screen has several secure features. First of all, it has a rapidly-moving animation, which does not show up on a screenshot. Second, the screen clearly displays the time the open bar ends. Finally, the screen displays the name and face of the person booking it. </h5>
          </div>
                    <div class="border"></div>
                  <div class="text-content">
                      <h2>How many drinks do people get?</h2>
            <h5>Grotto is about taking the pressure off, not encouraging speedy drinking. You can expect Grotto clients to have anywhere between 2 and 3 drinks per person, per hour.  </h5>
          </div>
                    <div class="border"></div>
                  <div class="text-content">
                      <h2>Can people share it with friends?</h2>
            <h5>Each patron needs his or her own app. But don’t worry- Grotto makes it easy for your patrons to share it, and we even give them a bonus whenever they do. </h5>
          </div>
                      <div class="border"></div>
                    <div class="text-content">
                        <h2>What if someone is drunk?</h2>
                        <h5>Just like if a normal patron has had too much, your staff can escort that patron out or refuse service. We’ll handle refund request out of our own pocket.</h5>
                    </div>
                    <div class="border"></div>                                        
                  <div class="text-content">
            <h5>Don't see an answer for what you're looking for?</h5>
                        <h5 class="margin-top40">Email <a href="mailto:team@grottoapp.com" class="highlight">team@grottoapp.com</a></h5>
          </div>                                        
                                                                              
                </div>
            </div>
        </div>  
          
    </section>
    <!--/General text-->

</div>
<footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center">
          <%=image_tag 'home/pineapple.png', :class => 'footer_logo' %>
        </div>
        <div class="col-sm-12">
          <ul class="quick-links">
            <li><%= link_to 'Faq', venues_faq_path %></li>
            <li><%= link_to 'Press Kit', presskit_users_path %></li>
            <li><%= link_to 'Terms', terms_users_path %></li>
            <li><p class="copyright">© Grotto 2015 <a href="#">Privacy Policy</a></p></li>
          </ul>    
        </div>
        <div class="col-sm-12"></div>         
      </div>  
    </div>     
</footer>
<!--/Site wrap-->

app/views/venues/index.html.erb
<div class="nav_top">
  <div class="logo">
    <a href="https://www.grottoapp.com">
      <%= image_tag 'home/logo_final.png', :id => 'pineapple' %>
    </a>
  </div> 
</div> 
<header id="header1">
  <div class="navigation-bar">
    <div class="container"></div>
    <div class="clear"></div>
  </div>
  <!-- /Menu -->

  <div class="container">
    <!--Header content-->
    <div class="tablet_header">
      <h1 id="mobile_header"> Grotto makes marketing a profitable art form. </h1>
      <h3 id="mobile_subtext"> Offer a tasting hour to new patrons and spread the good feeling.</h3>
      <a href="mailto:mike@grottoapp.com">
        <div class="refer" id="work_with"> 
          <p class="work_text">Work with Grotto</p> 
        </div>
      </a>
    </div>
  </div>
</header>
<div class="how_it_works">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-sm-push-5 wow fadeInDown">
        <h2 id="how_mobile_center">How it Works</h2>
        <ul class="features-pagination controls">
          <li class="active">Grotto suggests your bar because it fits with a patron's preferences for the evening</li>
          <li>New patrons pay a flat rate to try the bar for one hour </li>
          <li>Patrons show their Grotto screen when ordering </li>
          <li>Bar staff serves drink, rings as Grotto comp to keep track</li>
        </ul>
      </div>
      <div class="col-sm-5 col-sm-pull-7">
        <div class="slide-phone-holder">
          <%= image_tag 'home/how_screen.png', :class=>'holder' %>
          <div id="features-slider" class="images-list">                   
            <%= image_tag 'home/phone2.png', :class=>'screen', data: { index: "0" } %>
            <%= image_tag 'home/phone1.png', :class=>'screen', data: { index: "1" } %>
            <%= image_tag 'home/phone.jpg', :class=>'screen', data: { index: "2" } %>
            <%= image_tag 'home/phone.jpg', :class=>'screen', data: { index: "3" } %>
          </div>
        </div>
      </div>
    </div>
  </div>  
</div>
<div class="perks">
  <h3 class="perks_text" id="perks_text"> Perks </h3>
  <div class="perks-list">
    <ul class="perks_list">
      <li>Offer a great deal to new patrons</li><br>
      <li>Grotto patrons average 2-3 drinks per hour so it's always profitable </li><br>
      <li> Grotto patrons come in groups of 2 or 3 </li><br>
      <li> Grotto patrons leave a mandatory 20% tip </li><br>
    </ul>
  </div>
</div>
<div class="how_it_works">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-sm-push-5 wow fadeInDown">
        <h2 id="how_mobile_center">Easy Payments</h2>
        <p></p>
        <ul class="features-pagination controls">
          <li class="active paymentli"> Grotto charges patrons, pays you twice a week, and handles the back office. Forget checks, chargebacks, and lost credit cards. </li>
          <li class="active"id="paymentsli">Grotto charges the patrons, you'll never write checks again</li>
          <li>Payments are twice weekly, but we'll be rolling out daily soon </li>
          <li>Grotto hanldes all back office work - you'll never worry about chargebacks, lost cards, etc. </li>
        </ul>                    
      </div>
      <div class="col-sm-5 col-sm-pull-7">
        <%= image_tag 'home/dog-pineapple.png', :class=>'holder' %>
      </div>
    </div>
  </div>
</div>
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <%= image_tag 'home/footer_logo.png', :class=>'footer_logo footer_logo_mobile' %>
      </div>
      <div class="col-sm-12">
        <div class="col-sm-12">
          <ul class="quick-links">
            <li><%= link_to 'Faq', venues_faq_path %></li>
            <li><%= link_to 'Terms', terms_users_path %></li>
            <li><a href="#">Privacy Policy</a></p></li>
          </ul>    
        </div>
        <div class="col-sm-12"></div>         
      </div>  
    </div>
  </div>
</footer>